// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgmxfofgsxpteppkuaaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhnbXhmb2Znc3hwdGVwcGt1YWFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDQ3NzYsImV4cCI6MjA1ODM4MDc3Nn0.UK3k4mdFsnvnnWcAO-OsZKWKUgWMTkyuGZk4KbAx5NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);